apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: sa-role
  namespace: default
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
    verbs:
      - list
      - get
